# Site settings
title: from Blog import *
header-img: img/home-bg.jpg
email: Ajohnson88@gmail.com
description: "A blog about my quest to become a developer."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: Amjohnson88
github_username:  AmaxJ
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
