# Site settings
title: "#Alan Johnson"
header-img: "img/greenbanner.jpg"
email: Ajohnson88@gmail.com
description: "My blog and portfolio page"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: Amjohnson88
github_username:  AmaxJ
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
